spring:
  datasource:
    url: ${DB_URL}
    username: citus
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${CHATGPT_API_KEY}
#      chat:
#        options:
#          model: gpt-4o



redis:
  host: 13.209.80.146
  port: 6379
  password: 3333

jwt:
  secret-key: ${SECRET_KEY}
  access-token-expiration: 300000 # 5m
  refresh-token-expiration: 86400000 # 24h

server:
  port: 8088


springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs
  default-consumes-media-type: application/json
  auto-tag-classes: true
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html